server.port: 8001
mybatis.type-aliases-package: com.plkj.spectrum.bean
mybatis.mapper-locations: classpath:mapper/*.xml
# hive 数据源自定义配置
spring:
  datasource:
    url: jdbc:hive2://155.82.107.41:10000/spectrum?useUnicode=true&characterEncoding=utf8
    username: hive
    password: hive
    driver-class-name: org.apache.hive.jdbc.HiveDriver

#日志
#logging:
#  level:
#    com.plkj.spectrum.dao: debug