# hive 数据源自定义配置
hive:
#  url: jdbc:hive2://10.10.10.104:10000/cw
#  username: cw
#  password: cw
  url: jdbc:hive2://158.82.100.201:10000/spectrum
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  username: hive
  password: hive
server.port: 8001

## phoenix 数据源自定义配置
#phoenix:
#  enable: true
#  url: jdbc:phoenix:10.10.10.104
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
#  #username:
#  #password:
#  default-auto-commit: true
## Mybatis 配置
#spring.datasource.url=jdbc: hive2://10.10.10.104:10000/cw
#spring.datasource.username: cw
#spring.datasource.password: cw
#spring.datasource.driver-class-name: org.apache.hive.jdbc.HiveDriver
# 不写 mybatis-config.xml 这个配置文件时可以用下面的配置
mybatis.type-aliases-package: com.plkj.spectrum.bean
mybatis.mapper-locations: classpath:mapper/*.xml